### ISSUE TITLE
20181210 feekback

### ISSUE THREAD

**Issue by CherrymhZ** [CherrymhZ/Hello-World#4]
# 20181210 feekback

## Issue
[MarkDown语法教程](https://guides.github.com/features/mastering-markdown/)
1. - [] 将特定的Issue转换为Pull Request
2. 添加标签以便整理（建议Issue积攒到一定数量时，可根据所需进行添加标签管理）
3. 添加里程碑进行管理
4.复选形式：- [ ] 完成图片    - []  -[x]

## Pull Request
* 获取diff格式与patch格式：
   * Pull Request的URL + .diff
   * Pull Request的URL + .patch

## Conversation & Issue
* 引用评论
   * 选中想引用的评论然后按R键，被选的部分就会自动以评论语法写入评论文本框

**Comment by Still1** [comment]
OK！Well done.  +1
